doc: add security policy
pillarjs/.github pull request #2
Opened 2024-11-28 13:37 UTC by UlisesGascon

2024-11-28 14:27 UTC, bjohansebas commented
A reference to the Threat mode?

2025-01-14 19:46 UTC, wesleytodd requested changes

2025-01-14 19:46 UTC, wesleytodd commented on SECURITY.md
> +Report security bugs by emailing the lead maintainer in the Readme.md file.
I got the security email setup today. I was testing out some features of the lfx management of it, but we can start using it now even though I have not fully finished setting it up.

```suggestion
Report security bugs by emailing `express-security@lists.openjsf.org`.
```

2025-01-15 15:29 UTC, wesleytodd approved these changes

2025-01-15 17:47 UTC, merged